services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # HTTP порт Minio
      - "9001:9001"  # Console порт Minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
      - MINIO_SCANNER_SPEED=fastest
    tmpfs:
      - /data:rw,size=10M
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      retries: 3
      timeout: 10s

  minio-setup:
    image: minio/mc:latest
    container_name: minio-setup
    depends_on:
      - minio
    build:
      context: ./minio-setup
    volumes:
      - ./minio-setup/entrypoint.sh:/entrypoint.sh
    entrypoint: /bin/bash /entrypoint.sh
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    restart: "no"

  python-app:
    build: .
    container_name: python-app
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
      - MINIO_URL=http://minio:9000
    volumes:
      - .:/app
